/**
 * Curated, machine-validated pool of judo YouTube clips.
 *
 * Generated by scripts/fetch-judo-clips.mjs from scripts/clip-sources.json.
 * Each id was verified via YouTube oEmbed at generation time — only videos
 * that exist AND allow embedding are included. To refresh the list, run:
 *
 *   npm run clips:fetch
 *
 * If a clip later disables embedding, RewardClip will fail over to the next
 * one in the rotation; the player experience never gets stuck.
 */

export interface JudoClip {
  /** YouTube video id — the part after `v=` or after `youtu.be/`. */
  youtubeId: string
  /** Short, kid-friendly description shown above the video. */
  title: string
  /** Optional start time in seconds (default 0). */
  start?: number
}

export const CLIP_DURATION_SECONDS = 30

export const JUDO_CLIPS: JudoClip[] = [
  { youtubeId: "sU0YLRLHEnU", title: "History of Judo" },
  { youtubeId: "UrjPLuNtMy0", title: "This is Judo" },
  { youtubeId: "aQKb7rN_zsg", title: "Moscow Judo Grand Slam 090710" },
  { youtubeId: "inyxiptQL3U", title: "UCHIMATA" },
  { youtubeId: "yxqv8a_TlNQ", title: "SEOI OSOTO and KOSOTO COMBO" },
  { youtubeId: "y018SN63ulM", title: "RIBOUT UCHIMATA" },
  { youtubeId: "AIeagmi7yyY", title: "OSOTO GARI" },
  { youtubeId: "jUkSsOptWlw", title: "CHAMPION LEVEL Harai Goshi by Vlad Koulikov" },
  { youtubeId: "NgTb3qiYITM", title: "Uchi Mata Made EASY by Vlad Koulikov" },
  { youtubeId: "1zg7k46NljA", title: "How to do the Both Sleeved Osoto Gari Judo Technique by Satoshi Ishii" },
  { youtubeId: "0_Zhx_qVegA", title: "Satoshi Ishii's DEADLY Diving Osoto Gari Instructional" },
  { youtubeId: "ORt1zSBLPVY", title: "Satoshi Ishii's KILLER Kosoto Chain To Osoto Gari" },
  { youtubeId: "ErWEZr0M3c4", title: "Judo Movement With Gripping by Bobby Rich" },
  { youtubeId: "MeKIfv6Inn0", title: "Tai Otoshi Judo Technique by Bobby Rich" },
  { youtubeId: "9-us4L9_lmA", title: "Yoko Tomoe Nage vs Opposite Sided Opponent by Israel Hernandez" },
  { youtubeId: "zazCAtBYy6c", title: "Ippon Seoi Nage vs Opposite Sided Opponent by Israel Hernandez" },
  { youtubeId: "WdAr9Ip-wHA", title: "Zebeda on Reverse Seoi-Mage" },
  { youtubeId: "cd7Qv244XEA", title: "Parlati's Drop Ouchi" },
  { youtubeId: "zL1b8tV05jI", title: "Cardoso's (Legal) Leg-Block Tomoe Nage" },
  { youtubeId: "rknuZ2bfXPw", title: "Petit's Uchimata off the Sleeve" },
  { youtubeId: "KxnaA4PrjMA", title: "Milani's Ouchi Feint into Osoto" },
  { youtubeId: "J7eJK_gbvJk", title: "Epic newaza scramble in judo competition #judo #newaza" },
  { youtubeId: "MnUHoIYnXm8", title: "Sumi gaeshi in competition #judo #judothrows" },
  { youtubeId: "hqsizKMwC2c", title: "Perfectly timed tomoe nage to armbar" },
  { youtubeId: "rR8go92WYNo", title: "Huge seoi nage in BJJ comp" },
  { youtubeId: "KSKnDt_Cc8E", title: "One of my favorite short and sharp kettlebell workouts #judostrength #kettlebellworkout" },
]
