/**
 * Curated, machine-validated pool of judo YouTube clips.
 *
 * Generated by scripts/fetch-judo-clips.mjs from scripts/clip-sources.json.
 * Each id was verified via YouTube oEmbed at generation time — only videos
 * that exist AND allow embedding are included. To refresh the list, run:
 *
 *   npm run clips:fetch
 *
 * If a clip later disables embedding, RewardClip will fail over to the next
 * one in the rotation; the player experience never gets stuck.
 */

export interface JudoClip {
  /** YouTube video id — the part after `v=` or after `youtu.be/`. */
  youtubeId: string
  /** Short, kid-friendly description shown above the video. */
  title: string
  /** Optional start time in seconds (default 0). */
  start?: number
}

export const CLIP_DURATION_SECONDS = 30

export const JUDO_CLIPS: JudoClip[] = [
  { youtubeId: "Kksh3xrcoos", title: "Eat Healthy with Gigi Judo | Kids Song 🥕🍎" },
  { youtubeId: "JQTw78yuHrI", title: "Kind is cool | Be Kind 🥋🩷💫" },
  { youtubeId: "ixne0akFJ9Q", title: "Hello Around the World 🌍 🥋💫" },
  { youtubeId: "2NsZI4P8bJw", title: "STOP. LOOK. STAY SAFE." },
  { youtubeId: "tUP9TrkaAQs", title: "Team Gigi 💥 Strong Together 💫" },
  { youtubeId: "NcI2Xd_e6eQ", title: "✨ Gigi Judo Learns Body Parts! ✨" },
  { youtubeId: "OuI3WdjnRWQ", title: "Let’s Learn Shapes with Gigi Judo 🥋🩷💫" },
  { youtubeId: "HvX-8wCrYG0", title: "🚸 STOP ✋👀 LOOK BOTH WAYS 💗 Stay safe every day!" },
  { youtubeId: "1kCYYTHNtRE", title: "🥋 Gigi Judo & Big Feelings! 💖 Happy 😄 | Sad 😢 | Excited 🤩 | Frustrated 😤" },
  { youtubeId: "JXCOCFbMHCo", title: "Let’s learn judo basics 🥋💫🩷" },
  { youtubeId: "yIBtp9OBzo0", title: "If you’re happy and you know it…clap your hands 👏 💫✨" },
  { youtubeId: "YJjaY36hKXE", title: "🤍 Gigi Judo – Head & Shoulders | Open Arms 🥋" },
  { youtubeId: "cc56Z-AS40Y", title: "✨ Sparklesparkle, little light ✨" },
  { youtubeId: "GXuM8m1Wicw", title: "✨Sparkle Sparkle, Little Light | Gigi Judo Bedtime Song 🌙" },
  { youtubeId: "V4-i86koVyo", title: "Move & Stretch with GIGI JUDO 🥋 Part || 💫✨🩷 #gigijudo #kidssongs #toddlerlearning #nurseryrhymes" },
  { youtubeId: "r32Le4HDEnw", title: "Eltern-Kind-Judo beim Sport-Dojo Berlin e.V." },
  { youtubeId: "KYs7cuTMqWQ", title: "Fallschule at home // Sport-Dojo-Berlin 2021" },
  { youtubeId: "ahmkhD7VYU0", title: "Kata Elisa Wagner" },
  { youtubeId: "ZA6q2eDoMis", title: "Judo macht fit 12 - Zeitungsfechten" },
  { youtubeId: "zit_Vb1Z13c", title: "Judo macht fit 11 - Achterbahn" },
  { youtubeId: "I4fU5MWyM78", title: "Judo macht fit 10 - Die Arche Noah" },
  { youtubeId: "kdFcOr5TIo8", title: "Judo macht fit 9 - Der Drehwurm" },
  { youtubeId: "lEFzUikhm0I", title: "Judo macht fit 8 - Die Putzhilfe" },
  { youtubeId: "BRg4KC1RtMA", title: "Judo macht fit 7 - Gleichgewicht" },
  { youtubeId: "poMFL60gTkI", title: "Judo macht fit 6 - Guten Tag" },
  { youtubeId: "BO-uqaubpME", title: "Judo macht fit 5 - Propeller" },
  { youtubeId: "Ac8uPb5H9aE", title: "Judo macht fit 4 - Bank klettern" },
  { youtubeId: "ii7VenMXOlo", title: "Judo macht fit 3 - Schatz bewachen" },
  { youtubeId: "2ro27IG5Q64", title: "Judo macht fit 1 - Sockenklauen" },
  { youtubeId: "wxuqHupNqWg", title: "Judo macht fit 2 - Der Flieger" },
  { youtubeId: "sU0YLRLHEnU", title: "History of Judo" },
  { youtubeId: "UrjPLuNtMy0", title: "This is Judo" },
  { youtubeId: "aQKb7rN_zsg", title: "Moscow Judo Grand Slam 090710" },
  { youtubeId: "inyxiptQL3U", title: "UCHIMATA" },
  { youtubeId: "yxqv8a_TlNQ", title: "SEOI OSOTO and KOSOTO COMBO" },
  { youtubeId: "VSdG6zZVCmA", title: "SASAE" },
  { youtubeId: "y018SN63ulM", title: "RIBOUT UCHIMATA" },
  { youtubeId: "AIeagmi7yyY", title: "OSOTO GARI" },
  { youtubeId: "RoEBdJb21cM", title: "HARAI" },
  { youtubeId: "JBEPvItdK0Y", title: "令和8年講道館鏡開式　古式の形 / Kodokan Kagami Biraki ceremony 2026 Koshiki-no-Kata" },
  { youtubeId: "loxViHaUECw", title: "令和8年講道館鏡開式　五の形 / Kodokan Kagami Biraki ceremony 2026 Itsutsu-no-Kata" },
  { youtubeId: "Y3eydFDVhw0", title: "令和8年講道館鏡開式　講道館護身術 / Kodokan Kagami Biraki ceremony 2026 Kodokan Goshin-jutsu" },
  { youtubeId: "QRVAR2aLE-o", title: "令和8年講道館鏡開式　柔の形 / Kodokan Kagami Biraki ceremony 2026 Ju-no-Kata" },
  { youtubeId: "o_Xd_kteMzc", title: "令和8年講道館鏡開式　極の形 / Kodokan Kagami Biraki ceremony 2026 Kime-no-Kata" },
  { youtubeId: "oKaCgO0FdPk", title: "令和8年講道館鏡開式　固の形 / Kodokan Kagami Biraki ceremony 2026 Katame-no-Kata" },
  { youtubeId: "slJn4tN9sTw", title: "令和8年講道館鏡開式　投の形 / Kodokan Kagami Biraki ceremony 2026 Nage-no-Kata" },
  { youtubeId: "7aL640NhyA0", title: "令和7年講道館鏡開式　古式の形 / Kodokan Kagami Biraki ceremony 2025 Koshiki-no-Kata" },
  { youtubeId: "gsT7VFcQh3E", title: "令和7年講道館鏡開式　五の形 / Kodokan Kagami Biraki ceremony 2025 Itsutsu-no-Kata" },
  { youtubeId: "qevL9YVZsbo", title: "令和7年講道館鏡開式　講道館護身術 / Kodokan Kagami Biraki ceremony 2025 Kodokan Goshin-jutsu" },
  { youtubeId: "Nw-eADih5mo", title: "令和7年講道館鏡開式　柔の形 / Kodokan Kagami Biraki ceremony 2025 Ju-no-Kata" },
  { youtubeId: "vRALigvtyVM", title: "令和7年講道館鏡開式　極の形 / Kodokan Kagami Biraki ceremony 2025 Kime-no-Kata" },
  { youtubeId: "1-IXQ6RBpCo", title: "Sacrifice Hiza-guruma - Demo" },
  { youtubeId: "748RAYeDMMM", title: "Cross Body Osoto-gari - Demo" },
  { youtubeId: "-qzhPZUhs1s", title: "Ducking Kouchi-makikomi - Demo" },
  { youtubeId: "SVW6ARuOOY0", title: "Ankle Block Te-guruma - Demo" },
  { youtubeId: "3q110EX_1wY", title: "Two Sleeve Kata-guruma - Demo" },
  { youtubeId: "jUkSsOptWlw", title: "CHAMPION LEVEL Harai Goshi by Vlad Koulikov" },
  { youtubeId: "NgTb3qiYITM", title: "Uchi Mata Made EASY by Vlad Koulikov" },
  { youtubeId: "1zg7k46NljA", title: "How to do the Both Sleeved Osoto Gari Judo Technique by Satoshi Ishii" },
  { youtubeId: "FR-gUgGCfsM", title: "Spinning Harai by Bobby Rich" },
  { youtubeId: "rp39RzKoLUw", title: "Modified Ko Uchi Gake by Bobby Rich" },
  { youtubeId: "cxmaWXgT53w", title: "Koshi Guruma by Bobby Rich" },
  { youtubeId: "ErWEZr0M3c4", title: "Judo Movement With Gripping by Bobby Rich" },
  { youtubeId: "MeKIfv6Inn0", title: "Tai Otoshi Judo Technique by Bobby Rich" },
  { youtubeId: "9-us4L9_lmA", title: "Yoko Tomoe Nage vs Opposite Sided Opponent by Israel Hernandez" },
  { youtubeId: "L93ouw0c2wQ", title: "O Guruma vs Opposite Sided Opponent by Israel Hernandez" },
  { youtubeId: "zazCAtBYy6c", title: "Ippon Seoi Nage vs Opposite Sided Opponent by Israel Hernandez" },
  { youtubeId: "WdAr9Ip-wHA", title: "Zebeda on Reverse Seoi-Mage" },
  { youtubeId: "cd7Qv244XEA", title: "Parlati's Drop Ouchi" },
  { youtubeId: "zL1b8tV05jI", title: "Cardoso's (Legal) Leg-Block Tomoe Nage" },
  { youtubeId: "hOYsS9-9aAg", title: "Stojadinov's Uchi-Makikomi" },
  { youtubeId: "3cSiBo0wp28", title: "Ferreira's Sasae vs Sasae" },
  { youtubeId: "rknuZ2bfXPw", title: "Petit's Uchimata off the Sleeve" },
  { youtubeId: "KxnaA4PrjMA", title: "Milani's Ouchi Feint into Osoto" },
  { youtubeId: "EDlrBNosXrU", title: "Ippon seoi nage with Shintaro | JUDO" },
  { youtubeId: "nVbiCml3W10", title: "Tai Otoshi Made Easy! Step-by-Step with Sensei Shintaro | #judo #taiotoshi" },
  { youtubeId: "L8AJF9QmMkI", title: "Tall vs Short in Judo | The Shintaro Higashi Show" },
  { youtubeId: "gnSzGqyM_IQ", title: "Timing Beats Strength in Judo! | The Shintaro Higashi Show" },
  { youtubeId: "E_iv-tRhZBk", title: "Tall vs Short in Judo | The Shintaro Higashi Show" },
  { youtubeId: "mOZnEj28hZY", title: "The Timing Secret Most Judoka Miss! | The Shintaro Higashi Show" },
  { youtubeId: "oRLnerTmN-A", title: "American Judo Live Session" },
  { youtubeId: "wJMFQN6SF6o", title: "American Judo Live Session" },
  { youtubeId: "jwHRpuqvsHA", title: "MASTER THE KOUCHI MAKIKOMI! 🔥 JUDO SETUP & EXECUTION 🥋" },
  { youtubeId: "Wf7sb_bzxiE", title: "HOW TO COUNTER UCHIMATA LIKE A PRO! 🔥 JUDO TIPS WITH ISRAEL HERNANDEZ 🥋" },
  { youtubeId: "ODvoiuymI_M", title: "Brian Olson's Signature Foot Sweep Setup | Grip Break to Takedown" },
  { youtubeId: "b0t3L4BxvWw", title: "Counter Uchimata Like a Pro with Israel Hernandez | Judo Defense Mastery" },
  { youtubeId: "U-jDOheV92g", title: "Perfect Your Ippon Seoi Nage | Demonstration by an American Judo Athlete" },
  { youtubeId: "2VBppFLLWQo", title: "Master Reaction-Based Throws | American Judo Athlete Technique" },
  { youtubeId: "dYuKgOz5oto", title: "Expert Hip Movement | Israel Hernandez Judo Tips" },
  { youtubeId: "lsWByqF4ld0", title: "ARAI DOTA - Top Ippons! One of the best uchimatas in judo!　新井 道大" },
  { youtubeId: "kDAzf3XjPqk", title: "Who is VAMOS BOY?! One of my favorite judo YouTubers to watch!" },
  { youtubeId: "1_LW09cz4GU", title: "TOP IPPONS! Qazaqstan Judo GS 2026" },
  { youtubeId: "_dCglf8KsOo", title: "Qazaqstan Judo GS 2026 - Day 3 Highlights!" },
  { youtubeId: "ciXQVCePoBg", title: "Qazaqstan Judo GS 2026 - Day 2 Highlights!" },
  { youtubeId: "NKHIK3ax40Q", title: "Qazaqstan Judo GS 2026 - Day 1 Highlights!" },
  { youtubeId: "Bqu6PHBVFZ0", title: "TOP IPPONS - Dushanbe GS 2026" },
  { youtubeId: "OCnf5bZxZX0", title: "All Japan Judo Championship 2026 - ONE OF THE BEST EVER!!!" },
  { youtubeId: "InJE6EMdwBE", title: "Top Ippons European Judo Championships 2026 #judohighlights #judo" },
  { youtubeId: "xjdJ8CWIAak", title: "Top Ippons European Judo Championships 2026" },
  { youtubeId: "V6CVUrrY2YY", title: "European Judo Championships Day 4 Highlights!" },
]
